spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:restDocs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    url: /swagger/open-api-3.0.1.json
    path: /swagger
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#  cache:
#    disabled: true
